services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: crysterz/uvtsign:latest
    ports:
      - 3000:3000
    volumes:
      - .:/data
    environment:
      #FORCE_SSL=${HOST}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/uvtsign

  postgres:
    image: postgres:15
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uvtsign
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from http://${HOST} --to http://app:3000
    ports:
      - 80:80
    volumes:
      - .:/data

  # caddy:
  #   image: caddy:latest
  #   command: caddy reverse-proxy --from $HOST --to app:3000
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 443:443/udp
  #   volumes:
  #     - .:/data
  #   environment:
  #     - HOST=${HOST}
